config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :cards do
    patch :check, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  before_validation :capitalize_words
  before_create :set_next_review_date!

  validates :original_text, :translated_text, presence: true
  validate :translated_text_not_equal_original

  REVIEW_INTERVAL = 3

  scope :random_overdue_cards, -> { where('review_date_on <= ?', Time.current - REVIEW_INTERVAL.days).order("RANDOM()") }

  def set_next_review_date!
    self.review_date_on = REVIEW_INTERVAL.days.since
  end

  private

  def capitalize_words
    self.original_text   = original_text.to_s.strip.capitalize
    self.translated_text = translated_text.to_s.strip.capitalize
  end

  def translated_text_not_equal_original
    return unless original_text == translated_text
    msg = I18n.t('activerecord.errors.models.card.attributes.have_to_be_different')
    errors.add(:translated_text, msg)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_card, only: %i(show edit update destroy check)

  CARDS_PER_PAGE = 12

  def index
    @cards = Card.page(params[:page]).per(CARDS_PER_PAGE)
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      flash[:success] = t 'cards_messages.create_success'
      redirect_to @card
    else
      render :new
    end
  end

  def update
    if @card.update(card_params)
      flash[:success] = t 'cards_messages.update_success'
      redirect_to @card
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    flash[:success] = t 'cards_messages.destroy_success'
    redirect_to cards_path
  end

  def check
    if CardReviewService.new(@card, card_params[:translated_text]).review!
      flash[:success] = t 'cards_messages.translation_success'
      redirect_to root_path
    else
      flash[:error] = t 'cards_messages.translation_wrong'
      render 'pages/home'
    end
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text)
  end

  def find_card
    @card ||= Card.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# --------------------------------------
# Pages controller
# handles routes to pages that do not require CRUD methods
# --------------------------------------
class PagesController < ApplicationController
  def home
    @card = Card.random_overdue_cards.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_card.html.slim
.col-md-4
  .panel.panel-success
    .panel-heading
      .text-right
        = link_to fa_icon('edit'), edit_card_path(card), class: 'btn-edit'
      h3.text-center #{t 'card_panel.show_title'}#{card.id}
    .panel-body
      .row
        .col-md-6
          .lead.text-center = card.original_text
        .col-md-6
          .lead.text-center = card.translated_text
    .panel-footer
      .row
        .col-md-6
          .small = l card.review_date_on, format: :short
        .col-md-6.text-right
          = link_to fa_icon('close'), card_path(card), method: :delete, data: {confirm: t('card_panel.destroy_confirm_msg')}

app/views/cards/_form.html.slim
.container
  .row
    .col-md-6.col-md-offset-3      
      = simple_form_for @card do |f|
        f.error_notification
        .panel.panel-success
          .panel-heading
            h3.text-center = t("card_panel.#{action_name}_title").concat @card.id.to_s
          .panel-body
            .row
              .col-md-6
                = f.input :original_text, label: false, input_html: {class: 'input-lg'}
              .col-md-6
                = f.input :translated_text, label: false, input_html: {class: 'input-lg'}
              = f.input :review_date_on, as: :hidden
            .small
              = f.button :submit, class: 'btn btn-success form-control'

app/views/cards/edit.html.slim
= render 'form'

app/views/cards/index.html.slim
.container
  - @cards.each_slice(3) do |cards|
    .row
      .col-lg-12
        = render cards
  .text-center = paginate @cards

app/views/cards/new.html.slim
= render 'form'

app/views/cards/show.html.slim
.container
  = render @card

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/_card_translate.html.slim
.container
  .row
    .col-md-6.col-md-offset-3      
      = simple_form_for @card, url: check_card_path(@card) do |f|
        f.error_notification
        .panel.panel-success
          .panel-heading
            h3.text-center #{t("card_panel.show_title")} #{@card.id.to_s}
          .panel-body
            .row
              .col-md-6
                = f.input :original_text, label: false, readonly: true, input_html: {class: 'input-lg'}
              .col-md-6
                = f.input :translated_text, label: false, input_html: {value: '', class: 'input-lg'}
            .small
              = f.button :submit, t('card_panel.check'), class: 'btn btn-success form-control'

app/views/pages/_jumbotron.html.slim
.container
  .jumbotron
    h1 = t('home_page.app_name')
    p = t('home_page.app_description')
    p = link_to t('home_page.call_to_action'), new_card_path, class: 'btn btn-success btn-lg'

app/views/pages/home.html.slim
- if @card
  = render 'pages/card_translate'
- else
  = render 'pages/jumbotron'

app/views/shared/_messages.html.erb
<% unless flash.empty? %>
  <script type='text/javascript'>
    <% flash.each do |f| %>
      <% type = f.first.to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.slim
.container
  nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        = link_to t('navbar.brand'), root_path, class: 'navbar-brand'
      ul.nav.navbar-nav.navbar-right
        li= link_to t('navbar.all_cards'), cards_path
        li= link_to t('navbar.add_card'), new_card_path